version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Submit a single PR to update all GitHub action versions.
    groups:
      batch:
        patterns:
          - "*"
